name: Build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: \
                  cmake \
                  g++ \
                  libboost-serialization-dev \
                  libc++-dev \
                  libegl1-mesa-dev \
                  libepoxy-dev \
                  libgl1-mesa-dev \
                  libgles2-mesa-dev \
                  libglew-dev \
                  libopencv-dev nasm \
                  libwayland-dev \
                  libx11-dev \
                  libxkbcommon-dev \
                  ninja-build \
                  wayland-protocols
          version: 1.0

      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
          doNotCache: false

      # Note: if the preset misses the "configuration", it is possible to explicitly select the
      # configuration with the additional `--config` flag, e.g.:
      #   buildPreset: 'ninja-vcpkg'
      #   buildPresetAdditionalArgs: "[`--config`, `Release`]"
      #   testPreset: 'ninja-vcpkg'
      #   testPresetAdditionalArgs: "[`--config`, `Release`]"
      - name: Run CMake+vcpkg+Ninja+CTest to build packages and generate/build/test the code.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-vcpkg-release'
          testPreset: 'test-release'
