name: Build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libfmt-dev libg2o-dev libopencv-dev nasm \
                  libx11-dev libgles2-mesa-dev \
                  libgl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols libegl1-mesa-dev \
                  libc++-dev libepoxy-dev libglew-dev libeigen3-dev cmake g++ ninja-build
          version: 1.0

      - name: Build Pangolin with vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
          vcpkgGitCommitId: e3db8f65d2414c301c29a8467c6aee94e3ba09fc
          # Enable caching of built packages
          doNotCache: false

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: |
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg
